# Generated by Django 3.2.6 on 2021-08-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuarantorRelationShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_ref', models.CharField(max_length=200)),
                ('means_disbursed', models.CharField(choices=[('1', 'Cash'), ('2', 'Cheque'), ('3', 'Mpesa'), ('4', 'EFT')], default=None, max_length=1)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('loan_release_date', models.DateTimeField()),
                ('interest_method', models.CharField(choices=[('1', 'Flat Rate')], default=None, max_length=1)),
                ('interest_type', models.CharField(choices=[('1', 'Percentage Based'), ('2', 'Fixed amount per cycle')], default=None, max_length=1)),
                ('loan_interest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_cycle', models.CharField(choices=[('1', 'Per Day'), ('2', 'Per Week'), ('3', '2 weeks'), ('4', 'Monthly')], default=None, max_length=1)),
                ('loan_duration', models.IntegerField()),
                ('number_of_repayments', models.IntegerField()),
                ('loan_application_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('loan_status', models.CharField(choices=[('1', 'Initiated'), ('2', 'Pending Approval'), ('3', 'Approved'), ('4', 'Disbursed')], default='1', max_length=1)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.borrower')),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='loans.loanproduct')),
                ('repayment_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.repaymentcycle')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('other_names', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=200)),
                ('kra_pin', models.CharField(max_length=200)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='loans.loan')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.guarantorrelationship')),
            ],
        ),
    ]
