# Generated by Django 3.2.6 on 2021-09-14 09:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('documents_confirmation', models.BooleanField(blank=True)),
                ('credit_score_check', models.BooleanField(blank=True)),
                ('status', models.CharField(choices=[('1', 'Approve'), ('2', 'Reject')], max_length=1)),
                ('date_approved', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
            ],
        ),
    ]
