# Generated by Django 3.2.6 on 2021-08-26 08:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('other_name', models.CharField(max_length=300)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'Male')], default=1)),
                ('title', models.IntegerField(default=1, verbose_name=[(1, 'Mr'), (2, 'Mrs'), (3, 'Miss')])),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('dob', models.DateTimeField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('county', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=200)),
                ('alt_contact', models.CharField(blank=True, max_length=200)),
                ('credit_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('borrower_photo', models.ImageField(upload_to='photos/%Y/%m%d/')),
                ('description', models.TextField(blank=True)),
                ('borrower_files', models.FileField(blank=True, upload_to='borrower_files/%Y/%m%d/')),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
