# Generated by Django 3.2.6 on 2021-08-31 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.bank')),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('county', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrowers.county')),
            ],
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='address',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='alt_contact',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='city',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='county',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='borrower',
            name='id_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='borrower',
            name='id_upload',
            field=models.FileField(blank=True, upload_to='borrower_files/%Y/%m%d/'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='borrower',
            name='marital_status',
            field=models.CharField(choices=[('1', 'Single'), ('2', 'Married'), ('3', 'Divorced'), ('4', 'Widowed')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='borrower',
            name='nationality',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrower',
            name='number_of_children',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrower',
            name='number_of_dependants',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrower',
            name='pin_upload',
            field=models.FileField(blank=True, upload_to='borrower_files/%Y/%m%d/'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='title',
            field=models.IntegerField(choices=[(1, 'Mr'), (2, 'Mrs'), (3, 'Miss')], default=None),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sub_county', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrowers.subcounty')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('othernames', models.CharField(blank=True, max_length=200)),
                ('relationship', models.CharField(choices=[('1', 'Mother'), ('2', 'Father'), ('3', 'Brother'), ('4', 'Sister'), ('5', 'Relative'), ('6', 'Friend'), ('7', 'Guardian'), ('8', 'Wife'), ('9', 'Husband'), ('10', 'Employer')], default=None, max_length=2)),
                ('id_number', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('borrower', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrowers.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('alt_phone', models.CharField(max_length=200)),
                ('postal_address', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=200)),
                ('postal_city', models.CharField(blank=True, max_length=200)),
                ('nearest_landmark', models.CharField(blank=True, max_length=200)),
                ('family_surname', models.CharField(blank=True, max_length=200)),
                ('name_of_chief', models.CharField(blank=True, max_length=200)),
                ('name_of_ass_chief', models.CharField(blank=True, max_length=200)),
                ('road_street', models.CharField(blank=True, max_length=200)),
                ('estate', models.CharField(blank=True, max_length=200)),
                ('building_plot', models.CharField(blank=True, max_length=200)),
                ('house_office_no', models.CharField(blank=True, max_length=200)),
                ('Residence_Ownership', models.CharField(choices=[('1', 'Rented'), ('2', 'Owned')], default=None, max_length=1)),
                ('landlord_name', models.CharField(blank=True, max_length=200)),
                ('caretaker_agent_name', models.CharField(blank=True, max_length=200)),
                ('borrower', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrowers.borrower')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.county')),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.subcounty')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.ward')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('year_of_registration', models.DateTimeField(blank=True)),
                ('registration_number', models.CharField(max_length=200)),
                ('lincense_number', models.CharField(max_length=200)),
                ('number_of_employees', models.IntegerField(blank=True)),
                ('business_lincense', models.FileField(blank=True, upload_to='borrower_files/%Y/%m%d/')),
                ('certificate_of_incorporation', models.FileField(blank=True, upload_to='borrower_files/%Y/%m%d/')),
                ('kra_pin', models.CharField(max_length=200)),
                ('business_pin', models.FileField(blank=True, upload_to='borrower_files/%Y/%m%d/')),
                ('nature_of_business', models.TextField(blank=True)),
                ('borrower', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrowers.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=200)),
                ('eft', models.CharField(max_length=200)),
                ('mpesa_number', models.CharField(blank=True, max_length=200)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.bank')),
                ('bank_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowers.bankbranch')),
                ('borrower', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrowers.borrower')),
            ],
        ),
    ]
